CREATE USER 'team1'@'localhost' IDENTIFIED BY 'team1';
GRANT EXECUTE, PROCESS, SELECT, SHOW DATABASES, SHOW VIEW, ALTER, ALTER ROUTINE, CREATE, CREATE ROUTINE, CREATE TABLESPACE, CREATE TEMPORARY TABLES, CREATE VIEW, DELETE, DROP, EVENT, INDEX, INSERT, REFERENCES, TRIGGER, UPDATE, CREATE USER, FILE, LOCK TABLES, RELOAD, REPLICATION CLIENT, REPLICATION SLAVE, SHUTDOWN, SUPER  ON *.* TO 'team1'@'localhost' WITH GRANT OPTION;

CREATE TABLE `member` (
	`MEM_ID` VARCHAR(255) NULL DEFAULT NULL,
	`MEM_PW` VARCHAR(255) NULL DEFAULT NULL,
	`MEM_NAME` VARCHAR(255) NULL DEFAULT NULL,
	`MEM_POST` INT(11) NULL DEFAULT NULL,
	`MEM_ADDR` VARCHAR(255) NULL DEFAULT NULL,
	`MEM_TEL` VARCHAR(255) NULL DEFAULT NULL,
	`MEM_PHONE` VARCHAR(255) NULL DEFAULT NULL,
	`MEM_EMAIL` VARCHAR(255) NULL DEFAULT NULL
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB
;

CREATE TABLE `counselor` (
	`COUN_ID` VARCHAR(255) NULL DEFAULT NULL,
	`COUN_PW` VARCHAR(255) NULL DEFAULT NULL,
	`COUN_NAME` VARCHAR(255) NULL DEFAULT NULL,
	`COUN_POST` INT(11) NULL DEFAULT NULL,
	`COUN_ADDR` VARCHAR(255) NULL DEFAULT NULL,
	`COUN_TEL` VARCHAR(255) NULL DEFAULT NULL,
	`COUN_PHONE` VARCHAR(255) NULL DEFAULT NULL,
	`COUN_EMAIL` VARCHAR(255) NULL DEFAULT NULL,
	`COUN_DEPT` VARCHAR(255) NULL DEFAULT NULL,
	`COUN_TIME` VARCHAR(255) NULL DEFAULT NULL
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB
;

CREATE TABLE `reservation` (
	`MEM_ID` VARCHAR(255) NULL DEFAULT NULL,
	`COUN_ID` VARCHAR(255) NULL DEFAULT NULL,
	`RESE_TIME` DATE NULL DEFAULT NULL
)
ENGINE=InnoDB
;

CREATE TABLE `certification` (
	`CERT_ID` VARCHAR(255) NULL DEFAULT NULL,
	`CERT_PHONE` VARCHAR(255) NULL DEFAULT NULL,
	`CERT_NUMBER` INT(11) NULL DEFAULT NULL,
	`CERT_TIME` DATE NULL DEFAULT NULL
)
ENGINE=InnoDB
;

CREATE TABLE `board` (
	`BOAR_NO` INT(255) NULL DEFAULT NULL,
	`MEM_ID` VARCHAR(255) NULL DEFAULT NULL,
	`BOAR_TITLE`VARCHAR(255) DEFAULT NULL,
	`BOAR_CONT` VARCHAR(255) NULL DEFAULT NULL,
	`BOAR_TIME` DATE NULLNULL DEFAULT NULL,
	`BOAR_COUN` INT(255) NULL DEFAULT NULL
)
ENGINE=InnoDB
;

CREATE TABLE `comment` (
	`BORD_NO` INT(255) NULL DEFAULT NULL,
	`MEM_ID` VARCHAR(255) NULL DEFAULT NULL,
	`COMM_CONT` VARCHAR(255) NULL DEFAULT NULL,
	`COMM_TIME` DATE NULL DEFAULT NULL
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB
;

CREATE TABLE `psychological` (
	`PSYC_NO` INT(255) NULL DEFAULT NULL,
	`PSYC_TYPE` VARCHAR(255) NULL DEFAULT NULL
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB
;

CREATE TABLE `examination` (
	`PSYC_NO` INT(255) NULL DEFAULT NULL,
	`EXAM_CONT` VARCHAR(255) NULL DEFAULT NULL,
	`EXAM_SELE` INT(11) NULL DEFAULT NULL
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB
;

CREATE TABLE `grade` (
	`PSYC_NO` INT(255) NULL DEFAULT NULL,
	`GRAD_RATING` VARCHAR(255) NULL DEFAULT NULL
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB
;

CREATE TABLE `result` (
	`MEM_ID` VARCHAR(255) NULL DEFAULT NULL,
	`PSYC_NO` INT(255) NULL DEFAULT NULL,
	`RESU_TIME` DATE NULL DEFAULT NULL,
	`RESU_RESU` VARCHAR(255) NULL DEFAULT NULL
)
ENGINE=InnoDB
;